using UnityEngine;
using UnityEngine.UI;
public partial class missioneditor : BaseWin
{
	public missioneditor() { }
	public override string Prefab => "missioneditor";
	public GameObject _Root;
	public Button btn_back;
    public Button btn_save;
    public InputField input_id;
	public Button btn_get;
	public Button btn_creatPath;
	public Button btn_delPath;
	public Button btn_creatBranch;
	public Button btn_delBranch;
	public Button btn_delPoint;
    public Button btn_switch;
    public GameObject pathTag;
	public ScrollRect pathList;
	public ScrollRect branchList;
	public GameObject PointList;
	public GameObject PointItem;
	public GameObject pathroot;
	public Button btn_rolepoint;
    public Button btn_trap;
    public GameObject trapPanel;
    public GameObject rolePoint;
	public Button btn_outRolePoint;
	public Button btn_monster_panel;
	public GameObject monsterPanel;
	public Button MonsterPanelCopy;
	public Button MonsterPanelDelete;
	public Button MonsterPanelNew;
	public Button MonsterPanelUp;
	public Button MonsterPanelDown;
	public GameObject MonsterPanelContent_content;
	public GameObject MonsterInput;
	public Button MonsterPanelLast;
	public Button MonsterPanelNext;
	public Button MonsterPanelNewOne;
	public Button MonsterPanelDeleteOne;
	public Button MonsterPanelCopyNew;
	public Button MonsterPanelSave;
	public GameObject MonsterPanelContents;
	public Text waveIndexText;
	public Button btn_monsterMove;

    protected override void InitUI()
	{
		_Root = uiRoot;
		btn_back = _Root.transform.Find("btn_back").GetComponent<Button>();
        btn_save = _Root.transform.Find("btn_save").GetComponent<Button>();
        input_id = _Root.transform.Find("input_id").GetComponent<InputField>();
		btn_get = _Root.transform.Find("btn_get").GetComponent<Button>();
		btn_creatPath = _Root.transform.Find("btn_creatPath").GetComponent<Button>();
		btn_delPath = _Root.transform.Find("btn_delPath").GetComponent<Button>();
		btn_creatBranch = _Root.transform.Find("btn_creatBranch").GetComponent<Button>();
		btn_delBranch = _Root.transform.Find("btn_delBranch").GetComponent<Button>();
		btn_delPoint = _Root.transform.Find("btn_delPoint").GetComponent<Button>();
        btn_switch = _Root.transform.Find("btn_switch").GetComponent<Button>();
        btn_monsterMove = _Root.transform.Find("btn_monsterMove").GetComponent<Button>();
        pathTag = _Root.transform.Find("pathList/view/Content/pathTag").gameObject;
		pathList = _Root.transform.Find("pathList").GetComponent<ScrollRect>();
		branchList = _Root.transform.Find("branchList").GetComponent<ScrollRect>();
		btn_rolepoint = _Root.transform.Find("btn_rolepoint").GetComponent<Button>();
		btn_outRolePoint = _Root.transform.Find("rolePoint/btn_outRolePoint").GetComponent<Button>();
        btn_trap = _Root.transform.Find("btn_trap").GetComponent<Button>();
        trapPanel = _Root.transform.FindHideInChild("trapPanel").gameObject;
        rolePoint = _Root.transform.Find("rolePoint").gameObject;
        PointList = _Root.transform.Find("PointList").gameObject;
		PointItem = _Root.transform.Find("PointItem").gameObject;
        pathroot = _Root.transform.Find("pathroot").gameObject;
		btn_monster_panel = _Root.transform.Find("btn_monster_panel").GetComponent<Button>();
		monsterPanel = _Root.transform.Find("monsterPanel").gameObject;
		MonsterPanelCopy = monsterPanel.transform.Find("MonsterPanelCopy").GetComponent<Button>();
		MonsterPanelDelete = monsterPanel.transform.Find("MonsterPanelDelete").GetComponent<Button>();
		MonsterPanelNew = monsterPanel.transform.Find("MonsterPanelNew").GetComponent<Button>();
		MonsterPanelUp = monsterPanel.transform.Find("MonsterPanelUp").GetComponent<Button>();
		MonsterPanelDown = monsterPanel.transform.Find("MonsterPanelDown").GetComponent<Button>();
		MonsterPanelContents = monsterPanel.transform.Find("MonsterPanelContents").gameObject;
		MonsterPanelContent_content = monsterPanel.transform.Find("MonsterPanelContentDemo/Viewport/Content").gameObject;
		MonsterInput = monsterPanel.transform.Find("MonsterInput").gameObject;
		MonsterPanelLast = monsterPanel.transform.Find("MonsterPanelLast").GetComponent<Button>();
		MonsterPanelNext = monsterPanel.transform.Find("MonsterPanelNext").GetComponent<Button>();
		MonsterPanelNewOne = monsterPanel.transform.Find("MonsterPanelNewOne").GetComponent<Button>();
		MonsterPanelDeleteOne = monsterPanel.transform.Find("MonsterPanelDeleteOne").GetComponent<Button>();
		MonsterPanelCopyNew = monsterPanel.transform.Find("MonsterPanelCopyNew").GetComponent<Button>();
		MonsterPanelSave = monsterPanel.transform.Find("MonsterPanelSave").GetComponent<Button>();
		btn_back.onClick.AddListener(btn_back_Click);
		btn_get.onClick.AddListener(btn_get_Click);
		btn_creatPath.onClick.AddListener(btn_creatPath_Click);
		btn_delPath.onClick.AddListener(btn_delPath_Click);
		btn_creatBranch.onClick.AddListener(btn_creatBranch_Click);
		btn_delBranch.onClick.AddListener(btn_delBranch_Click);
		btn_delPoint.onClick.AddListener(btn_delPoint_Click);
		btn_save.onClick.AddListener(btn_save_Click);
		btn_switch.onClick.AddListener(btn_switch_Click);
		btn_rolepoint.onClick.AddListener(btn_rolepoint_Click);
        btn_trap.onClick.AddListener(btn_trap_Click);
        btn_outRolePoint.onClick.AddListener(btn_outRolePoint_Click);
		btn_monster_panel.onClick.AddListener(btn_monster_panel_Click);
		MonsterPanelCopy.onClick.AddListener(MonsterPanelCopy_Click);
		MonsterPanelDelete.onClick.AddListener(MonsterPanelDelete_Click);
		MonsterPanelNew.onClick.AddListener(MonsterPanelNew_Click);
		MonsterPanelUp.onClick.AddListener(MonsterPanelUp_Click);
		MonsterPanelDown.onClick.AddListener(MonsterPanelDown_Click);
		MonsterPanelLast.onClick.AddListener(MonsterPanelLast_Click);
		MonsterPanelNext.onClick.AddListener(MonsterPanelNext_Click);
		MonsterPanelNewOne.onClick.AddListener(MonsterPanelNewOne_Click);
		MonsterPanelDeleteOne.onClick.AddListener(MonsterPanelDeleteOne_Click);
		MonsterPanelCopyNew.onClick.AddListener(MonsterPanelCopyNew_Click);
		MonsterPanelSave.onClick.AddListener(MonsterPanelSave_Click);
		btn_monsterMove.onClick.AddListener(btn_monsterMove_Click);

    }
	partial void btn_back_Click();
	partial void btn_get_Click();
	partial void btn_creatPath_Click();
	partial void btn_delPath_Click();
	partial void btn_creatBranch_Click();
	partial void btn_delBranch_Click();
	partial void btn_delPoint_Click();
    partial void btn_save_Click();
    partial void btn_switch_Click();
    partial void btn_rolepoint_Click();
    partial void btn_trap_Click();
    partial void btn_outRolePoint_Click();
	partial void btn_monster_panel_Click();
	partial void MonsterPanelCopy_Click();
	partial void MonsterPanelDelete_Click();
	partial void MonsterPanelNew_Click();
	partial void MonsterPanelUp_Click();
	partial void MonsterPanelDown_Click();
	partial void MonsterPanelLast_Click();
	partial void MonsterPanelNext_Click();
	partial void MonsterPanelNewOne_Click();
	partial void MonsterPanelDeleteOne_Click();
	partial void MonsterPanelCopyNew_Click();
	partial void MonsterPanelSave_Click();
	partial void btn_monsterMove_Click();
}
